<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEtablissementsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('etablissements', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('universite_id');
            $table->string('intitule')->default('Universite Virtuelle de Tunis');
            $table->string('abrev')->default('UVT');;
            $table->integer('gid');
//            $table->foreign('universite_id')->references('id')->on('universites');
        });

        DB::table('etablissements')->insert (
            [ 'id' =>'01'   ,'universite_id' =>'01'  ,'intitule' =>'Institut Superieure Exmpl' , 'abrev' => 'EtabExmpl' , 'gid' => '1000']

        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('etablissements');
    }
}
//
//-- Table structure for table `etablissement`--
//INSERT INTO `etablissements` VALUES
//(16,34,'Institut SupÃ©rieur de Civilisation Islamique de Tunis','isci',1091),
//(15,34,'Institut SupÃ©rieur de ThÃ©ologie de Tunis','isth',1092),
//(17,34,'Centre des Etudes Islamiques de Kairouan','ceik',1093),
//(18,35,'FacultÃ© des Sciences Juridiques, Politiques et Sociales de Tunis','fsjpst',1094),
//(19,35,'FacultÃ© des Sciences de Bizerte','fsb',1095),
//(20,35,'FacultÃ© des Sciences Economiques et de Gestion de Nabeul','fsegn',1096),
//(21,35,'Ecole Nationale d\'Architecture et d\'Urbanisme de Tunis','enaut',1097),
//(22,35,'Ecole Polytechnique de Tunisie','ept',1098),
//(23,35,'Ecole SupÃ©rieure de Technologie et d\'Informatique Ã  Carthage','esti',1099),
//(24,35,'Ecole SupÃ©rieure des Statistiques et d\'Analyse de l\'Information','essai',1100),
//(25,35,'Ecole SupÃ©rieure de l\'Audiovisuel et du CinÃ©ma de Gammarth','esac',1101),
//(26,35,'Institut PrÃ©paratoire aux Etudes d\'IngÃ©nieur de Bizerte','ipeib',1102),
//(27,35,'Institut des Hautes Etudes Commerciales de Carthage','ihec',1103),
//(28,35,'Institut National des Sciences AppliquÃ©es et de Technologie','insat',1104),
//(29,35,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de la Technologie de Mateur','issatm',1105),
//(30,35,'Institut PrÃ©paratoire aux Etudes d\'IngÃ©nieur Nabeul','ipein',1106),
//(31,35,'Institut PrÃ©paratoire aux Etudes Scientifiques et Techniques de la Marsa','ipest',1107),
//(32,35,'Institut SupÃ©rieur des Beaux Arts de Nabeul','isban',1108),
//(33,35,'Institut SupÃ©rieur des Technologies de l\'Environnement, de L\'Urbanisme et du BÃ¢timent','isteub',1109),
//(34,35,'Institut SupÃ©rieur des Langues de Tunis','islt',1110),
//(35,35,'Institut SupÃ©rieur des Langues AppliquÃ©es et d\'Informatique de Nabeul','islain',1111),
//(36,35,'Institut SupÃ©rieur des Sciences et Technologies de l\'Environnement de Borj CÃ©dria','isste',1112),
//(37,35,'Institut SupÃ©rieur de Commerce et de ComptabilitÃ© de Bizerte','isccb',1113),
//(38,35,'Sup\'Com','supcom',1114),(39,35,'Ecole SupÃ©rieure d\'Agriculture de Mograne','esam',1115),
//(40,35,'Ecole SupÃ©rieure d\'Agriculture de Mateur','esa',1116),
//(41,35,'Ecole SupÃ©rieure des Industries Alimentaires de Tunis','esiat',1117),
//(42,35,'Institut SupÃ©rieur de PÃªche et d\'Aquaculture de Bizerte','ispab',1118),
//(43,35,'Institut National du Travail et des Etudes Sociales de Tunis','intes',1119),
//(44,35,'Institut SupÃ©rieur des Cadres de l\'Enfance','iscenf',1120),
//(45,35,'Institut National Agronomique de Tunis','inat',1121),
//(46,35,'Institut SupÃ©rieur des Etudes Touristique de Sidi Dhrif','ihet',1122),
//(47,35,'Institut SupÃ©rieur d\'Etudes PrÃ©paratoires en Biologie et GÃ©ologie de la Soukra','isepbgs',1123),
//(48,35,'Institut National de Recherche en GÃ©nie Rural, Eau et ForÃªt','inrgref',1124),
//(49,35,'Institut National de Recherche Agronomique de Tunis','inrat',1125),
//(50,38,'FacultÃ© des Sciences Humaines et Sociales de Tunis','fshst',1126),
//(51,38,'Ecole Normale SupÃ©rieure','ens',1127),
//(52,38,'Ecole SupÃ©rieure des Sciences Economiques et Commerciales de Tunis','essec',1128),
//(53,38,'Ecole SupÃ©rieure des Sciences et Techniques de Tunis','esstt',1129),
//(54,38,'Institut PrÃ©paratoire aux Etudes d\'IngÃ©nieurs de Tunis','ipeit',1130),
//(55,38,'Institut PrÃ©paratoire aux Etudes LittÃ©raires et de Sciences Humaines de Tunis','ipelsht',1131),
//(56,38,'Institut SupÃ©rieur de Gestion de Tunis','isg',1132),
//(57,38,'Institut SupÃ©rieur des Beaux Arts de Tunis','isbat',1133),
//(58,38,'Institut SupÃ©rieur de Musique','ismt',1134),
//(59,38,'Institut SupÃ©rieur d\'Art Dramatique','isad',1135),
//(60,30,'Institut SupÃ©rieur de l\'Education et de la Formation Continue','isefc',1136),
//(61,38,'Institut SupÃ©rieur des Sciences Culturelles et MÃ©tiers du Patrimoine de Tunis','isscmpt',1137),
//(62,38,'Institut SupÃ©rieur des Etudes AppliquÃ©es en HumanitÃ© de Tunis','iseaht',1138),
//(63,38,'Institut SupÃ©rieur de l\'Animation pour la Jeunesse et la Culture','isajc',1139),
//(64,38,'Institut SupÃ©rieur des Ã‰tudes AppliquÃ©es en HumanitÃ©s de Zaghouan','iseahz',1140),
//(65,38,'Institut National du Patrimoine','inp',1141),
//(66,31,'FacultÃ© de Droit et des Sciences Politiques de Tunis','fdspt',1142),
//(67,31,'FacultÃ© de MÃ©decine de Tunis','fmt',1143),
//(68,31,'FacultÃ© des Sciences Economique et de Gestion de Tunis','fsegt',1144),
//(69,31,'FacultÃ© des Sciences MathÃ©matiques, Physiques et Naturelles de Tunis','fst',1145),
//(70,31,'Ecole Nationale d\'IngÃ©nieurs de Tunis','enit',1146),
//(71,31,'Institut Bourguiba des Langues Vivantes','iblv',1147),
//(72,31,'Institut PrÃ©paratoire aux Etudes d\'IngÃ©nieurs d\'El Manar','ipeiem',1148),
//(73,31,'Institut SupÃ©rieur des Sciences Biologiques AppliquÃ©es','issbat',1149),
//(74,31,'Institut SupÃ©rieur d\'Informatique d\'El Manar','isi',1150),
//(75,31,'Institut SupÃ©rieur des Sciences Humaines de Tunis','issht',1151),
//(76,31,'Institut SupÃ©rieur des Technologies MÃ©dicales','istmt',1152),
//(77,31,'Ecole SupÃ©rieure des Sciences et Techniques de la SantÃ© de Tunis','paramedicalis',1153),
//(78,31,'Institut SupÃ©rieur des Sciences infirmiÃ¨res de Tunis','issit',1154),
//(79,31,'Institut Pasteur','is',1155),
//(80,31,'Institut de Recherche VÃ©tÃ©rinaire de Tunis','irvt',1156),
//(81,39,'FacultÃ© des Lettres, des Arts et des HumanitÃ©s de la Manouba','flm',1157),
//(82,39,'Ecole SupÃ©rieure des Sciences et Technologies du Design','essted',1158),
//(83,39,'Ecole SupÃ©rieure de Commerce de Tunis','esct',1159),
//(84,39,'Ecole SupÃ©rieure de Commerce Electronique de la Manouba','escem',1160),
//(85,39,'Ecole Nationale des Sciences de l\'Informatique','ensi',1161),
//(86,39,'Institut SupÃ©rieur des Arts du MultimÃ©dia de la Manouba','isa2m',1162),
//(87,39,'Institut SupÃ©rieur de ComptabilitÃ© et d\'Administration des Entreprises','iscae',1163),
//(88,39,'Institut SupÃ©rieur de Biotechnologie de Sidi Thabet','isbst',1164),
//(89,39,'Institut SupÃ©rieur de Documentation de Tunis','isd',1165),
//(90,39,'Institut de Presse et des Sciences de l\'Information','ipsi',1166),
//(91,39,'Ecole Nationale de MÃ©decine VÃ©tÃ©rinaire de Sidi Thabet','enmv',1167),
//(92,39,'Institut SupÃ©rieur du Sport et de l\'Education Physique de Ksar SaÃ¯d','issep',1168),
//(93,39,'Institut SupÃ©rieur de Promotion des HandicapÃ©s de Ksar SaÃ¯d','iph',1169),
//(94,39,'Institut SupÃ©rieur d\'Histoire du Mouvement National','ishmn',1170),
//(95,43,'FacultÃ© des Sciences Juridiques, Economiques et de Gestion de Jendouba','fsjegj',1171),
//(96,43,'Institut SupÃ©rieur des Etudes AppliquÃ©es en HumanitÃ©s du Kef','iseahkf',1172),
//(97,43,'Institut SupÃ©rieur des Langues AppliquÃ©es et Informatique de BÃ©ja','islaib',1173),
//(98,43,'Institut SupÃ©rieur des Sciences Humaines de Jendouba','isshj',1174),
//(99,43,'Institut supÃ©rieur des arts et mÃ©tiers de Siliana','isams',1175),
//(100,43,'Institut supÃ©rieur de musique et de thÃ©Ã¢tre du Kef','ismtk',1176),
//(101,43,'Institut supÃ©rieur de l\'informatique du Kef','isik',1177),
//(102,43,'Institut supÃ©rieur de biotechnologie de BÃ©ja','isbb',1178),
//(103,43,'Institut SupÃ©rieur de l\'Education Physique du Kef','isepk',1179),
//(104,43,'Ecole SupÃ©rieure d\'Agriculture du Kef','iresa',1180),
//(105,43,'Institut Sylvo-Pastoral de Tabarka','ispt',1181),
//(106,43,'Ecole SupÃ©rieure des IngÃ©nieurs de l\'Equipement Rural de Medjez El Bab','esier',1182),
//(107,43,'Institut SupÃ©rieur des Sciences infirmiÃ¨res du Kef','issik',1183),
//(108,36,'FacultÃ© de Droit et des Sciences Economiques et Politiques de Sousse','fdseps',1184),
//(109,36,'FacultÃ© de MÃ©decine de Sousse','medecinesousse',1185),
//(110,36,'FacultÃ© des Lettres et des Sciences Humaines de Sousse','fls',1186),
//(111,36,'Institut des Hautes Etudes Commerciales de Sousse','ihecso',1187),
//(112,36,'Institut SupÃ©rieur de Finances et de FiscalitÃ© de Sousse','isffs',1188),
//(113,36,'Institut SupÃ©rieur des Beaux Arts de Sousse','isbas',1189),
//(114,36,'Institut SupÃ©rieur de Gestion de Sousse','isgs',1190),
//(115,36,'Institut SupÃ©rieur d\'Informatique et des Technologies  de Communication de Hammam Sousse','infcom',1191),
//(116,36,'Institut SupÃ©rieur de Musique de Sousse','ismso',1192),
//(117,36,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de Technologie de Sousse','issatso',1193),
//(118,36,'Institut SupÃ©rieur du Transport et de la Logistique de Sousse','istls',1194),
//(119,36,'Ecole Nationale dâ€™IngÃ©nieurs de Sousse','eniso',1195),
//(120,36,'Ecole SupÃ©rieure des Sciences et des technologies de Hammam Sousse','essths',1196),
//(121,36,'Ecole SupÃ©rieure d\'Horticulture et d\'Elevage de Chott Meriem','isacm',1197),
//(122,36,'Ecole SupÃ©rieure des Sciences et Techniques de la SantÃ© de Sousse','esstss',1198),
//(123,36,'Institut SupÃ©rieur des Sciences infirmiÃ¨res de Sousse','issis',1199),
//(124,40,'FacultÃ© des Sciences de Monastir','fsm',1200),
//(125,40,'FacultÃ© de MÃ©decine de Monastir','fmm',1201),
//(126,40,'FacultÃ© de MÃ©decine  Dentaire de Monastir','fmdm',1202),
//(127,40,'FacultÃ© de Pharmacie de Monastir','fphm',1203),
//(128,40,'FacultÃ© des Sciences Economiques et de Gestion de Mahdia','fsegma',1204),
//(129,40,'Ecole Nationale d\'IngÃ©nieurs de Monastir','enim',1205),
//(130,40,'Institut PrÃ©paratoire aux Etudes d\'IngÃ©nieurs de Monastir','ipeim',1206),
//(131,40,'Institut SupÃ©rieur de Biotechnologie de Monastir','isbm',1207),
//(132,40,'Institut SupÃ©rieur d\'Informatique et de MathÃ©matiques de Monastir','isimm',1208),
//(133,40,'Institut SupÃ©rieur des MÃ©tiers de la Mode de Monastir','ismmm',1209),
//(134,40,'Institut SupÃ©rieur des Langues AppliquÃ©es aux Affaires et au Tourisme de Moknine','islaatm',1210),
//(135,40,'Institut SupÃ©rieur des Etudes AppliquÃ©es en HumanitÃ©s de Mahdia','iseahm',1211),
//(136,40,'Institut SupÃ©rieur d\'Informatique  de Mahdia','isima',1212),
//(137,40,'Institut supÃ©rieur des Arts et MÃ©tiers de Mahdia','isamm',1213),
//(138,40,'Institut supÃ©rieur des sciences appliquÃ©es et de technologie de Mahdia','issatmh',1214),
//(139,40,'Ecole SupÃ©rieure des Sciences et Techniques de la SantÃ© de Monastir','esstsm',1215),
//(140,44,'FacultÃ© des Lettres et des Sciences Humaines de Kairouan','flshk',1216),
//(141,44,'Institut SupÃ©rieur des Arts et MÃ©tiers de Kairouan','isamk',1217),
//(142,44,'Institut SupÃ©rieur d\'Informatique et de Gestion de Kairouan','isigk',1218),
//(143,44,'Institut SupÃ©rieur des Etudes Juridiques et Politiques de Kairouan','isejpk',1219),
//(144,44,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de Technologie de Kairouan','issatkr',1220),
//(145,44,'Institut SupÃ©rieur des Arts et MÃ©tiers de Kasserine','isamkas',1221),
//(146,44,'Institut SupÃ©rieur des MathÃ©matiques AppliquÃ©es et de l\'Informatique de Kairouan','ismaik',1222),
//(147,37,'FacultÃ© des Sciences Economiques et de Gestion de Sfax','fsegs',1223),
//(148,37,'FacultÃ© de MÃ©decine de Sfax','fmsf',1224),
//(149,37,'FacultÃ© des Lettres et Sciences Humaines de Sfax','flshs',1225),
//(150,37,'FacultÃ© des Sciences de Sfax','fss',1226),
//(151,37,'FacultÃ© de Droit de Sfax','fdsf',1227),
//(152,37,'Ecole Nationale d\'IngÃ©nieurs de Sfax','enis',1228),
//(153,37,'Ecole SupÃ©rieure de Commerce de Sfax','escs',1229),
//(154,37,'Institut des Hautes Etudes Commerciales de Sfax','ihecsf',1230),
//(155,37,'Institut SupÃ©rieur d\'Administration des Affaires de Sfax','isaas',1231),
//(156,37,'Institut SupÃ©rieur des Arts et MÃ©tiers de Sfax','isamsf',1232),
//(157,37,'Institut SupÃ©rieur de Biotechnologies de Sfax','isbs',1233),
//(158,37,'Ecole Nationale d\'Electronique et T&eacute;l&eacute;communications de Sfax','isecs',1234),
//(159,37,'Institut SupÃ©rieur d\'Informatique et de MultimÃ©dia de Sfax','isimsf',1235),
//(160,37,'Institut SupÃ©rieur de Gestion Industrielle de Sfax','isgis',1236),
//(161,37,'Institut SupÃ©rieur de Musique de Sfax','ismsf',1237),
//(162,37,'Institut Pr&eacute;paratoire aux Etudes d\'Ing&eacute;nieurs de Sfax','ipeis',1238),
//(163,37,'Institut Zitouna de Sfax','izs',1239),
//(164,37,'Institut SupÃ©rieur du Sport et de l\'Education Physique de Sfax','issepsf',1240),
//(165,37,'Ecole SupÃ©rieure des Sciences et Techniques de la SantÃ© de Sfax','esstssf',1241),
//(166,37,'Institut SupÃ©rieur des Sciences infirmiÃ¨res  de Sfax','issisf',1242),
//(167,41,'FacultÃ© des Sciences de Gafsa','fsgf',1243),
//(168,41,'Institut SupÃ©rieur des Etudes AppliquÃ©es en HumanitÃ©s de Gafsa','iseahg',1244),
//(169,41,'Institut SupÃ©rieur d\'Administration des Entreprises de Gafsa','isaeg',1245),
//(170,41,'Institut SupÃ©rieur dâ€™Arts et mÃ©tiers de Gafsa','isamgf',1246),
//(171,41,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de Technologie de Gafsa','issatg',1247),
//(172,41,'Institut SupÃ©rieur des Sciences et des Technologies de l\'Ã©nergie de Gafsa','issteg',1248),
//(173,41,'Institut SupÃ©rieur des Etudes AppliquÃ©es en HumanitÃ©s de Tozeur','iseahtz',1249),
//(174,41,'Institut SupÃ©rieur du Sport et de l\'Education Physique de Gafsa','issepg',1250),
//(175,45,'FacultÃ© des Sciences de GabÃ¨s','fsg',1251),(176,45,'Ecole Nationale d\'IngÃ©nieurs de GabÃ¨s','enig',1252),
//(177,45,'Institut SupÃ©rieur de Biologie AppliquÃ©e de Medenine','isbam',1253),
//(178,45,'Institut SupÃ©rieur des Etudes Juridiques de GabÃ¨s','isejg',1254),
//(179,45,'Institut SupÃ©rieur des Arts et MÃ©tiers de GabÃ¨s','isamgb',1255),
//(180,45,'Institut SupÃ©rieur d\'Informatique et de MultimÃ©dia de GabÃ¨s','isimg',1256),
//(181,45,'Institut SupÃ©rieur de Gestion de GabÃ¨s','isggb',1257),
//(182,45,'Institut SupÃ©rieur des Langues de GabÃ¨s','islgb',1258),
//(183,45,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de Technologie de GabÃ¨s','issatgb',1259),
//(184,45,'Institut SupÃ©rieur des Sciences et Techniques des Eaux de GabÃ¨s','isstegb',1260),
//(185,45,'Institut supÃ©rieur des systÃ¨mes industriels de GabÃ¨s','issigb',1261),
//(186,45,'Institut supÃ©rieur des Ã©tudes appliquÃ©es en HumanitÃ©s de MÃ©denine','iseahmd',1262),
//(187,45,'Institut SupÃ©rieur d\'Informatique  de Medenine','isimd',1263),
//(188,45,'Institut SupÃ©rieur des Arts et MÃ©tiers de Tataouine','isamtt',1264),
//(189,45,'Institut SupÃ©rieur des Sciences infirmiÃ¨res  de GabÃ¨s','issig',1265),
//(190,42,'Institut SupÃ©rieur des Etudes Technologiques de BÃ©ja','isetbj',1266),
//(191,42,'Institut SupÃ©rieur des Etudes Technologiques de Charguia','isetch',1267),
//(192,42,'Institut SupÃ©rieur des Etudes Technologiques de GabÃ¨s','isetgb',1268),
//(193,42,'Institut SupÃ©rieur des Etudes Technologiques de Gafsa','isetgf',1269),
//(194,42,'Institut SupÃ©rieur des Etudes Technologiques de Jendouba','isetj',1270),
//(195,42,'Institut SupÃ©rieur des Etudes Technologiques de Jerba','isetjb',1271),
//(196,42,'Institut SupÃ©rieur des Etudes Technologiques de Kairouan','isetkr',1272),
//(197,42,'Institut SupÃ©rieur des Etudes Technologiques de Kasserine','isetka',1273),
//(198,42,'Institut SupÃ©rieur des Etudes Technologiques du Kef','isetkf',1274),
//(199,42,'Institut SupÃ©rieur des Etudes Technologiques de Ksar Hellal','isetkh',1275),
//(200,42,'Institut SupÃ©rieur des Etudes Technologiques de Kebili','isetke',1276),
//(201,42,'Institut SupÃ©rieur des Etudes Technologiques de Mahdia','isetma',1277),
//(202,42,'Institut SupÃ©rieur des Etudes Technologiques de Nabeul','isetn',1278),
//(203,42,'Institut SupÃ©rieur des Etudes Technologiques de RadÃ¨s','isetr',1279),
//(204,42,'Institut SupÃ©rieur des Etudes Technologiques de Sfax','isetsf',1280),
//(205,42,'Institut SupÃ©rieur des Etudes Technologiques de Sidi Bouzid','isetsbz',1281),
//(206,42,'Institut SupÃ©rieur des Etudes Technologiques de Siliana','isetsl',1282),
//(207,42,'Institut SupÃ©rieur des Etudes Technologiques de Sousse','isetso',1283),
//(208,42,'Institut SupÃ©rieur des Etudes Technologiques de Tataouine','isetta',1284),
//(209,42,'Institut SupÃ©rieur des Etudes Technologiques de Tozeur','isett',1285),
//(210,42,'Institut SupÃ©rieur des Etudes Technologiques de Zaghouan','isetzg',1286),
//(211,42,'Institut SupÃ©rieur des Etudes Technologiques de Bizerte','isetb',1287),
//(212,42,'Institut supÃ©rieur des Etudes Technologiques de MÃ©denine','isetmd',1288),
//(213,42,'Institut SupÃ©rieur des Etudes Technologiques en Communications (El Ghazala)','isetcom',1289),
//(222,30,'UniversitÃ© Viruelle De Tunis','puvt',1290),(223,46,'IHET','IHET',0),
//(224,42,'Institut SupÃ©rieur des Etudes Technologiques de Kelibia','isetklb',1290),
//(225,44,'FacultÃ© des Sciences et techniques de Sidi Bouzid','fstsb',1223),
//(226,44,'Institut SupÃ©rieur des Etudes AppliquÃ©es en Sciences Humaines de SbeÃ¯tla','iseashsb',1224),
//(227,44,'Institut SupÃ©rieur des Arts et MÃ©tiers de Sidi Bouzid','isamsd',1225),
//(228,44,'Institut SupÃ©rieur des Sciences AppliquÃ©es et de Technologie de Kasrine','issatkasr',1226),
//(229,35,'Institut SupÃ©rieur des Technologies de lâ€™Information et de la Communicatiom','istic',1091),
//(230,38,'Tunis Business School','TBS',1222),
//(231,41,'Ecole Nationale des Ingenieurs de Gafsa','ENIG',1292);
